image: dh-iutl.univ-artois.fr/gradle:8.12.0-jdk-21-and-23-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - package

default:
  tags:
    - 2024_virtuav

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

services:
  - dh-iutl.univ-artois.fr/mongo:8.0

build:
  stage: build
  script:
    - gradle clean build -x test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - gradle test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - build
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml

package:
  stage: package
  script:
    - gradle bootJar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main