services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: picit-api
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://picit-mongo:27017/picit
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    container_name: picit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
