spring:
  profiles:
    active: env

  application:
    name: picit-api
  data:
    mongodb:
      database: PicIt

server:
  port: 8081

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:secret-key}
    expiration-time: 86400000 # 1 day in milliseconds
    refresh-time: 604800000 # 1 week in milliseconds